In [10]:
import pandas as pd
import numpy as np

# Load the Excel file
file_path = 'MacPherson Feeding Logs (1).xlsx'
file_path2 = 'ghg-emission-factors-hub-2024 (1).xlsx'


# Read the specific sheet
#df = pd.read_excel(file_path, sheet_name='Jul to Dec 2024')
ref = pd.read_excel(file_path2, sheet_name='My Use')
df = pd.read_excel(file_path,sheet_name='Jan to Jun 2024')
copy = df.copy()

# Display the first few rows of the dataframe to check the data
df.head()

,Date,Tank 1,Tank 1 - CO2,Tank 2,Tank 2 - CO2,Tank 3,Tank 3 - CO2,Tank 4,Tank 4 - CO2,Tank 5,Tank 5 - CO2,pH values of worm feed
0,2024-01-15,"50g of distilled water, 1 spoon of dried radis...",0.0002,"100g of distilled water, 15g coffee grounds, 1...",0.00325,"100g of distilled water, 15g coffee grounds, 1...",0.00325,"100g of distilled water, 15g coffee grounds, 1...",0.00015,"100g of distilled water, 15g coffee grounds, 1...",0.00015,6.5
1,2024-01-16,NaN,NaN,"40g of distilled water, 20g of cardboard",0.00400,NaN,NaN,NaN,NaN,20g of cardboard,0.00400,NaN
2,2024-01-17,40g of distilled water,0.0000,40g of distilled water,0.00000,NaN,NaN,"40g of distilled water, 20g of cardboard",0.00400,40g of distilled water,0.00000,NaN
3,2024-01-18,20g of cardboard,0.0040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-01-19,"100g of distilled water, 1 spoon of dried radi...",0.0002,"100g of distilled water, 15g coffee grounds, 1...",0.00325,"100g of distilled water, 15g coffee grounds, 1...",0.00325,"100g of distilled water, 15g coffee grounds, 1...",0.00325,"100g of distilled water, 15g coffee grounds, 1...",0.00325,8

In [11]:
ref

,Material,RecycledA,LandfilledB,CombustedC,CompostedD,Anaerobically Digested (Dry Digestate with Curing)E,Anaerobically Digested (Wet Digestate with Curing)E
0,Aluminum Cans,0.06,0.02,0.01,NaN,NaN,NaN
1,Aluminum Ingot,0.04,0.02,0.01,NaN,NaN,NaN
2,Steel Cans,0.32,0.02,0.01,NaN,NaN,NaN
3,Copper Wire,0.18,0.02,0.01,NaN,NaN,NaN
4,Glass,0.05,0.02,0.01,NaN,NaN,NaN
...,...,...,...,...,...,...,...
56,Drywall,NaN,0.02,NaN,NaN,NaN,NaN
57,Fiberglass Insulation,0.05,0.02,NaN,NaN,NaN,NaN
58,Structural Steel,0.04,0.02,NaN,NaN,NaN,NaN
59,Vinyl Flooring,NaN,0.02,0.29,NaN,NaN,NaN
60,Wood Flooring,NaN,0.18,0.08,NaN,NaN,NaN

### Data formatting

# Drop the first row (now header) and reset index
ref = ref.drop(0).reset_index(drop=True)

# Set the first row as the header
header_row = ref.iloc[0]  # Get the first row
ref.columns = [str(col).strip() for col in header_row]  # Set the first row as column names and clean them up
ref = ref[0]  # Remove the first row from the DataFrame

# Reset the index of the DataFrame
ref.reset_index(drop=True, inplace=True)

# Display the updated DataFrame to verify changes
ref.head()

### Transformation

In [12]:
ref['Material'] = ref['Material'].str.lower()

# Display the updated DataFrame to verify changes
ref

,Material,RecycledA,LandfilledB,CombustedC,CompostedD,Anaerobically Digested (Dry Digestate with Curing)E,Anaerobically Digested (Wet Digestate with Curing)E
0,aluminum cans,0.06,0.02,0.01,NaN,NaN,NaN
1,aluminum ingot,0.04,0.02,0.01,NaN,NaN,NaN
2,steel cans,0.32,0.02,0.01,NaN,NaN,NaN
3,copper wire,0.18,0.02,0.01,NaN,NaN,NaN
4,glass,0.05,0.02,0.01,NaN,NaN,NaN
...,...,...,...,...,...,...,...
56,drywall,NaN,0.02,NaN,NaN,NaN,NaN
57,fiberglass insulation,0.05,0.02,NaN,NaN,NaN,NaN
58,structural steel,0.04,0.02,NaN,NaN,NaN,NaN
59,vinyl flooring,NaN,0.02,0.29,NaN,NaN,NaN
60,wood flooring,NaN,0.18,0.08,NaN,NaN,NaN

In [13]:
# Drop rows where 'CompostedD' has null values
ref = ref.dropna(subset=['CompostedD'])

# Display the cleaned DataFrame to verify changes
ref

,Material,RecycledA,LandfilledB,CombustedC,CompostedD,Anaerobically Digested (Dry Digestate with Curing)E,Anaerobically Digested (Wet Digestate with Curing)E
12,pla,NaN,0.02,0.01,0.13,NaN,NaN
21,food waste (non-meat),NaN,0.67,0.05,0.11,0.14,0.11
22,food waste (meat only),NaN,0.69,0.05,0.11,0.14,0.11
23,beef,NaN,0.64,0.05,0.11,0.14,0.11
24,poultry,NaN,0.73,0.05,0.11,0.14,0.11
25,grains,NaN,2.06,0.05,0.11,0.14,0.11
26,bread,NaN,1.49,0.05,0.11,0.14,0.11
27,fruits and vegetables,NaN,0.28,0.05,0.11,0.14,0.11
28,dairy products,NaN,0.72,0.05,0.11,0.14,0.11
29,yard trimmings,NaN,0.36,0.05,0.14,0.11,NaN
30,grass,NaN,0.28,0.05,0.14,0.09,NaN
31,leaves,NaN,0.28,0.05,0.14,0.12,NaN
32,branches,NaN,0.58,0.05,0.14,0.15,NaN
39,food waste,NaN,0.68,0.05,0.11,NaN,NaN
40,mixed organics,NaN,0.54,0.05,0.13,NaN,NaN

In [14]:
import re

# Function to process tank values
def process_tank_value(value):
    if pd.isna(value):
        return value
    
    # Find all numbers (integer or decimal) before 'g' and divide them by 1000
    def replace_number(match):
        number = float(match.group(1))
        return f"{number / 1000}g"
    
    # Update regex to capture decimal numbers
    processed_value = re.sub(r'(\d+(\.\d+)?)g', replace_number, str(value))
    return processed_value

# Apply the function to all tank columns
tank_columns = ['Tank 1', 'Tank 2', 'Tank 3', 'Tank 4']
for col in tank_columns:
    df[col] = df[col].apply(process_tank_value)

# Display the updated DataFrame to verify changes
df.head()

,Date,Tank 1,Tank 1 - CO2,Tank 2,Tank 2 - CO2,Tank 3,Tank 3 - CO2,Tank 4,Tank 4 - CO2,Tank 5,Tank 5 - CO2,pH values of worm feed
0,2024-01-15,"0.05g of distilled water, 1 spoon of dried rad...",0.0002,"0.1g of distilled water, 0.015g coffee grounds...",0.00325,"0.1g of distilled water, 0.015g coffee grounds...",0.00325,"0.1g of distilled water, 0.015g coffee grounds...",0.00015,"100g of distilled water, 15g coffee grounds, 1...",0.00015,6.5
1,2024-01-16,NaN,NaN,"0.04g of distilled water, 0.02g of cardboard",0.00400,NaN,NaN,NaN,NaN,20g of cardboard,0.00400,NaN
2,2024-01-17,0.04g of distilled water,0.0000,0.04g of distilled water,0.00000,NaN,NaN,"0.04g of distilled water, 0.02g of cardboard",0.00400,40g of distilled water,0.00000,NaN
3,2024-01-18,0.02g of cardboard,0.0040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-01-19,"0.1g of distilled water, 1 spoon of dried radi...",0.0002,"0.1g of distilled water, 0.015g coffee grounds...",0.00325,"0.1g of distilled water, 0.015g coffee grounds...",0.00325,"0.1g of distilled water, 0.015g coffee grounds...",0.00325,"100g of distilled water, 15g coffee grounds, 1...",0.00325,8

In [16]:
# Function to split, filter, and format each entry
def process_entry(entry):
    if isinstance(entry, str):
        items = [item.strip() for item in entry.split(',')]
        filtered_items = [item for item in items if 'spoon' not in item]
        return ''.join([f'[{item}]' for item in filtered_items])
    else:
        return np.nan

# Apply function to each tank column
df['Tank 1'] = df['Tank 1'].apply(process_entry)
df['Tank 2'] = df['Tank 2'].apply(process_entry)
df['Tank 3'] = df['Tank 3'].apply(process_entry)
df['Tank 4'] = df['Tank 4'].apply(process_entry)
#df['Tank 5'] = df['Tank 5'].apply(process_entry)

# Create a new DataFrame with Date and processed tank data
new_df = pd.DataFrame({
    'Date': df['Date'],
    'Tank 1': df['Tank 1'],
    'Tank 2': df['Tank 2'],
    'Tank 3': df['Tank 3'],
    'Tank 4': df['Tank 4'],
    #'Tank 5': df['Tank 5']
})
new_df

,Date,Tank 1,Tank 2,Tank 3,Tank 4
0,2024-01-15,[0.05g of distilled water][0.004g of crushed e...,[0.1g of distilled water][0.015g coffee ground...,[0.1g of distilled water][0.015g coffee ground...,[0.1g of distilled water][0.015g coffee ground...
1,2024-01-16,NaN,[0.04g of distilled water][0.02g of cardboard],NaN,NaN
2,2024-01-17,[0.04g of distilled water],[0.04g of distilled water],NaN,[0.04g of distilled water][0.02g of cardboard]
3,2024-01-18,[0.02g of cardboard],NaN,NaN,NaN
4,2024-01-19,[0.1g of distilled water][0.004g of crushed eg...,[0.1g of distilled water][0.015g coffee ground...,[0.1g of distilled water][0.015g coffee ground...,[0.1g of distilled water][0.015g coffee ground...
...,...,...,...,...,...
163,2024-06-26,NaN,NaN,NaN,NaN
164,2024-06-27,[0.05g coffee grounds],[0.05g coffee grounds],[0.05g coffee grounds],[0.05g coffee grounds]
165,2024-06-28,NaN,NaN,NaN,NaN
166,2024-06-29,[0.04g of distilled water],[0.04g of distilled water],[0.04g of distilled water],[0.04g of distilled water]
167,2024-06-30,NaN,NaN,NaN,NaN

In [17]:
# Convert all string values in the DataFrame to lowercase
new_df = new_df.applymap(lambda x: x.lower() if isinstance(x, str) else x)

new_df

C:\Users\junro\AppData\Local\Temp\ipykernel_1944\1745015262.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  new_df = new_df.applymap(lambda x: x.lower() if isinstance(x, str) else x)

,Date,Tank 1,Tank 2,Tank 3,Tank 4
0,2024-01-15,[0.05g of distilled water][0.004g of crushed e...,[0.1g of distilled water][0.015g coffee ground...,[0.1g of distilled water][0.015g coffee ground...,[0.1g of distilled water][0.015g coffee ground...
1,2024-01-16,NaN,[0.04g of distilled water][0.02g of cardboard],NaN,NaN
2,2024-01-17,[0.04g of distilled water],[0.04g of distilled water],NaN,[0.04g of distilled water][0.02g of cardboard]
3,2024-01-18,[0.02g of cardboard],NaN,NaN,NaN
4,2024-01-19,[0.1g of distilled water][0.004g of crushed eg...,[0.1g of distilled water][0.015g coffee ground...,[0.1g of distilled water][0.015g coffee ground...,[0.1g of distilled water][0.015g coffee ground...
...,...,...,...,...,...
163,2024-06-26,NaN,NaN,NaN,NaN
164,2024-06-27,[0.05g coffee grounds],[0.05g coffee grounds],[0.05g coffee grounds],[0.05g coffee grounds]
165,2024-06-28,NaN,NaN,NaN,NaN
166,2024-06-29,[0.04g of distilled water],[0.04g of distilled water],[0.04g of distilled water],[0.04g of distilled water]
167,2024-06-30,NaN,NaN,NaN,NaN

### Replacing Food Item that u know are incorrectly named or does not follow naming in Emission Index

In [ ]:
# Replace 'wombok' and 'cabbage' with 'napa cabbage' across all columns
new_df = new_df.applymap(lambda x: x.replace('coffee grinds', 'coffee grounds').replace('egg shell', 'eggshells') if isinstance(x, str) else x)

new_df

In [18]:
ref = ref.applymap(lambda x: x.lower() if isinstance(x, str) else x)

ref

C:\Users\junro\AppData\Local\Temp\ipykernel_1944\1630056625.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  ref = ref.applymap(lambda x: x.lower() if isinstance(x, str) else x)

,Material,RecycledA,LandfilledB,CombustedC,CompostedD,Anaerobically Digested (Dry Digestate with Curing)E,Anaerobically Digested (Wet Digestate with Curing)E
12,pla,NaN,0.02,0.01,0.13,NaN,NaN
21,food waste (non-meat),NaN,0.67,0.05,0.11,0.14,0.11
22,food waste (meat only),NaN,0.69,0.05,0.11,0.14,0.11
23,beef,NaN,0.64,0.05,0.11,0.14,0.11
24,poultry,NaN,0.73,0.05,0.11,0.14,0.11
25,grains,NaN,2.06,0.05,0.11,0.14,0.11
26,bread,NaN,1.49,0.05,0.11,0.14,0.11
27,fruits and vegetables,NaN,0.28,0.05,0.11,0.14,0.11
28,dairy products,NaN,0.72,0.05,0.11,0.14,0.11
29,yard trimmings,NaN,0.36,0.05,0.14,0.11,NaN
30,grass,NaN,0.28,0.05,0.14,0.09,NaN
31,leaves,NaN,0.28,0.05,0.14,0.12,NaN
32,branches,NaN,0.58,0.05,0.14,0.15,NaN
39,food waste,NaN,0.68,0.05,0.11,NaN,NaN
40,mixed organics,NaN,0.54,0.05,0.13,NaN,NaN

### Checking Invalid Food Types that are not Identified

In [21]:
import re
import numpy as np
import pandas as pd

# Example DataFrames
# ref = pd.DataFrame({
#     'Food Name': ['eggshell', 'banana', 'beef'],
#     'Emissions (kg CO2/kg)': [0.01, 0.4, 27.0]
# })

# new_df = pd.DataFrame({
#     'Tank 1': ['100g of crushed eggshell', '50g of banana'],
#     'Tank 2': ['200g of beef', '150g of eggshell'],
#     'Tank 3': ['30g of banana', '20g of egg shells']
# })

# Convert emission data to a dictionary for easy lookup
emissions_dict = ref.set_index('Material')['CompostedD'].to_dict()

# Function to calculate the carbon offset for a given entry
def calculate_carbon_offset(entry):
    if pd.isna(entry):
        return np.nan
    # Extract food items and amounts
    items = re.findall(r'\[(.*?)\]', entry.lower())
    total_offset = 0
    for item in items:
        # Extract amount and food name
        match = re.match(r'(\d+\.?\d*)g (.*)', item)
        if match:
            amount = float(match.group(1))  # Amount in grams
            food_name = match.group(2).strip()  # Normalize food name
            # Check if any key from emissions_dict is in food_name
            matched = False
            for key in emissions_dict:
                if key in food_name:
                    offset = emissions_dict[key] * (amount)  # Convert grams to kg
                    total_offset += offset
                    matched = True
                    break
            if not matched:
                print(f"No match found for: {food_name}")
    return total_offset

# Apply the function to each tank column and date
for tank in ['Tank 1', 'Tank 2', 'Tank 3','Tank 4']:
    new_df[f'{tank} - C02'] = new_df[tank].apply(calculate_carbon_offset)

new_df

No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of cardboard
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of cardboard
No match found for: of cardboard
No match found for: distilled water
No match found for: of crushed eggshells
No match found for: distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: of cardboard
No match found for: of distilled water
No match found for: of distilled water
No match found for: of spinach
No match found for: of distilled water
No match found for: of spinach
No match found for: of distilled water
No match found for: of distilled water
No match found for: of cauliflower
No match found for: of banana peels
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of banana peels
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: of banana peels
No match found for: coffee grounds
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of cardboard
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of cardboard
No match found for: of distilled water
No match found for: of cardboard
No match found for: of distilled water
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of cardboard
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of cardboard
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of cardboard
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of cardboard
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: of cardboard
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: of distilled water
No match found for: of cardboard
No match found for: of cardboard
No match found for: of distilled water
No match found for: of spinach
No match found for: of distilled water
No match found for: of distilled water
No match found for: of kale
No match found for: of distilled water
No match found for: of distilled water
No match found for: of cauliflower
No match found for: of banana peels
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of banana peels
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: of banana peels
No match found for: coffee grounds
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of cardboard
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of cardboard
No match found for: of distilled water
No match found for: of crushed eggshells. 0.02g of cardboard
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: of cardboard
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: of distilled water
No match found for: of cardboard
No match found for: of distilled water
No match found for: of distilled water
No match found for: of spinach
No match found for: of distilled water
No match found for: of distilled water
No match found for: of kale
No match found for: of distilled water
No match found for: of cauliflower
No match found for: of banana peels
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of banana peels
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: of banana peels
No match found for: coffee grounds
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of cardboard
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of cardboard
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of cardboard
No match found for: of distilled water
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of cardboard
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of cardboard
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of cardboard
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of crushed eggshells
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: of distilled water
No match found for: of coffee grounds (dry)
No match found for: of distilled water
No match found for: of cardboard
No match found for: of cardboard
No match found for: of distilled water
No match found for: of spinach
No match found for: of distilled water
No match found for: of distilled water
No match found for: of cauliflower
No match found for: of distilled water
No match found for: of distilled water
No match found for: of cauliflower
No match found for: of banana peels
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of banana peels
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: of banana peels
No match found for: coffee grounds
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water
No match found for: coffee grounds
No match found for: of distilled water

,Date,Tank 1,Tank 2,Tank 3,Tank 4,Tank 1 - C02,Tank 2 - C02,Tank 3 - C02,Tank 4 - C02
0,2024-01-15,[0.05g of distilled water][0.004g of crushed e...,[0.1g of distilled water][0.015g coffee ground...,[0.1g of distilled water][0.015g coffee ground...,[0.1g of distilled water][0.015g coffee ground...,0.0,0.0,0.0,0.0
1,2024-01-16,NaN,[0.04g of distilled water][0.02g of cardboard],NaN,NaN,NaN,0.0,NaN,NaN
2,2024-01-17,[0.04g of distilled water],[0.04g of distilled water],NaN,[0.04g of distilled water][0.02g of cardboard],0.0,0.0,NaN,0.0
3,2024-01-18,[0.02g of cardboard],NaN,NaN,NaN,0.0,NaN,NaN,NaN
4,2024-01-19,[0.1g of distilled water][0.004g of crushed eg...,[0.1g of distilled water][0.015g coffee ground...,[0.1g of distilled water][0.015g coffee ground...,[0.1g of distilled water][0.015g coffee ground...,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
163,2024-06-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,2024-06-27,[0.05g coffee grounds],[0.05g coffee grounds],[0.05g coffee grounds],[0.05g coffee grounds],0.0,0.0,0.0,0.0
165,2024-06-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,2024-06-29,[0.04g of distilled water],[0.04g of distilled water],[0.04g of distilled water],[0.04g of distilled water],0.0,0.0,0.0,0.0
167,2024-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
new_df

,Date,Tank 1,Tank 2,Tank 3,Tank 4,Tank 1 - C02,Tank 2 - C02,Tank 3 - C02,Tank 4 - C02
0,2024-05-30,[1/3 of big leaf],[1/3 of big leaf],[1/3 of big leaf],[-],0.0000,0.000000,0.000000,0.000000
1,2024-06-03,[1 paper coffee filter][1/3 of big leaf],[1 paper coffee filter][1/3 of big leaf],[1 paper coffee filter][1/3 of big leaf],[-],0.0000,0.000000,0.000000,0.000000
2,2024-06-06,,,,[-],0.0000,0.000000,0.000000,0.000000
3,2024-06-10,,,,[-],0.0000,0.000000,0.000000,0.000000
4,2024-06-18,,,,[-],0.0000,0.000000,0.000000,0.000000
5,2024-06-18,,,,[-],0.0000,0.000000,0.000000,0.000000
6,2024-06-20,,,,[-],0.0000,0.000000,0.000000,0.000000
7,2024-06-27,,,,[-],0.0000,0.000000,0.000000,0.000000
8,2024-07-01,,,,[-],0.0000,0.000000,0.000000,0.000000
9,2024-07-04,[1 leaf],,[1 leaf],[-],0.0000,0.000000,0.000000,0.000000
10,2024-07-08,[0.015g egg carton cardboard],[0.015g eggshells],[0.0075g eggshellss][0.0075g egg carton cardbo...,[-],0.0030,0.000750,0.001875,0.000000
11,2024-07-11,[-],[0.015g eggshells],[0.0075g eggshellss][0.0075g egg carton cardbo...,[0.0075g eggshellss][0.015g egg carton cardboard],0.0000,0.000750,0.001875,0.003375
12,2024-07-18,[0.015g egg carton cardboard],[0.015g coffee grounds],[0.0075g coffee grounds][0.0075g egg carton ca...,[0.0075g coffee grounds][0.015g egg carton car...,0.0030,0.003000,0.003000,0.004500
13,2024-07-22,[0.0075g egg carton cardboard],[0.0075g eggshells],[0.0075g coffee grounds][0.0075g egg carton ca...,[0.0075g coffee grounds][0.015g egg carton car...,0.0015,0.000375,0.003000,0.004500
14,2024-07-25,[0.0075g egg carton cardboard],[0.0075g eggshells],[0.0075g coffee grounds][0.0075g egg carton ca...,[0.0075g coffee grounds][0.0075g egg carton ca...,0.0015,0.000375,0.003000,0.003000
15,2024-07-29,[0.0075g egg carton cardboard],[0.015g coffee grounds],[0.015g coffee grounds][0.0075g egg carton car...,[0.0075g coffee grounds][0.015g egg carton car...,0.0015,0.003000,0.004500,0.004500

In [13]:
# Merge DataFrames on 'Food Item'
merged_df = pd.merge(copy, new_df, on='Date', how='inner')

selected_columns = merged_df[['Date', 'Tank 1_x','Tank 1 - C02', 'Tank 2_x','Tank 2 - C02','Tank 3_x','Tank 3 - C02','Tank 4_x','Tank 4 - C02']]

# Rename columns to remove '_x' suffix
selected_columns = selected_columns.rename(columns={
    'Tank 1_x': 'Tank 1',
    'Tank 2_x': 'Tank 2',
    'Tank 3_x': 'Tank 3',
    'Tank 4_x': 'Tank 4'
})

selected_columns

,Date,Tank 1,Tank 1 - C02,Tank 2,Tank 2 - C02,Tank 3,Tank 3 - C02,Tank 4,Tank 4 - C02
0,2024-05-30,"2 spoonful of coffee grinds, 1/3 of big leaf",0.0000,"2 spoonful of coffee grinds, 1/3 of big leaf",0.000000,"2 spoonful of coffee grinds, 1/3 of big leaf",0.000000,-,0.000000
1,2024-06-03,"2 spoonful of coffee grinds, 1 paper coffee fi...",0.0000,"2 spoonful of coffee grinds, 1 paper coffee fi...",0.000000,"2 spoonful of coffee grinds, 1 paper coffee fi...",0.000000,-,0.000000
2,2024-06-06,2 spoonful of coffee grinds,0.0000,2 spoonful of eggshells,0.000000,"2 spoonful of coffee, 2 spoonful of eggshells",0.000000,-,0.000000
3,2024-06-10,2 spoonful of coffee grinds,0.0000,2 spoonful of eggshells,0.000000,"1 spoonful of coffee, 1 spoonful of eggshells",0.000000,-,0.000000
4,2024-06-18,2 spoonful of coffee grinds,0.0000,2 spoonful of eggshells,0.000000,"1 spoonful of coffee, 1 spoonful of eggshells",0.000000,-,0.000000
5,2024-06-18,2 spoonful of coffee grinds,0.0000,2 spoonful of eggshells,0.000000,"1 spoonful of coffee, 1 spoonful of eggshells",0.000000,-,0.000000
6,2024-06-18,2 spoonful of coffee grinds,0.0000,2 spoonful of eggshells,0.000000,"1 spoonful of coffee, 1 spoonful of eggshells",0.000000,-,0.000000
7,2024-06-18,2 spoonful of coffee grinds,0.0000,2 spoonful of eggshells,0.000000,"1 spoonful of coffee, 1 spoonful of eggshells",0.000000,-,0.000000
8,2024-06-20,2 spoonful of coffee grinds,0.0000,2 spoonful of eggshells,0.000000,"1 spoonful of coffee, 1 spoonful of eggshells",0.000000,-,0.000000
9,2024-06-27,2 spoonful of coffee grinds,0.0000,2 spoonful of eggshells,0.000000,"1 spoonful of coffee, 1 spoonful of eggshells",0.000000,-,0.000000
10,2024-07-01,2 spoonful of coffee grinds,0.0000,2 spoonful of eggshells,0.000000,"1 spoonful of coffee, 1 spoonful of eggshells",0.000000,-,0.000000
11,2024-07-04,1 leaf,0.0000,2 spoonful of eggshells,0.000000,"1 spoonful of eggshells, 1 leaf",0.000000,-,0.000000
12,2024-07-08,15g egg carton cardboard,0.0030,15g egg shell,0.000750,"7.5g egg shells, 7.5g egg carton cardboard",0.001875,-,0.000000
13,2024-07-11,-,0.0000,15g egg shell,0.000750,"7.5g egg shells, 7.5g egg carton cardboard",0.001875,"7.5g egg shells, 15g egg carton cardboard",0.003375
14,2024-07-18,15g egg carton cardboard,0.0030,15g coffee grinds,0.003000,"7.5g coffee grinds, 7.5g egg carton cardboard",0.003000,"7.5g coffee grinds, 15g egg carton cardboard",0.004500
15,2024-07-22,7.5g egg carton cardboard,0.0015,7.5g egg shell,0.000375,"7.5g coffee grinds, 7.5g egg carton cardboard",0.003000,"7.5g coffee grinds, 15g egg carton cardboard",0.004500
16,2024-07-25,7.5g egg carton cardboard,0.0015,7.5g egg shell,0.000375,"7.5g coffee grinds, 7.5g egg carton cardboard",0.003000,"7.5g coffee grinds, 7.5g egg carton cardboard",0.003000
17,2024-07-29,7.5g egg carton cardboard,0.0015,15g coffee grinds,0.003000,"15g coffee grinds, 7.5g egg carton cardboard",0.004500,"7.5g coffee grinds, 15g egg carton cardboard",0.004500

In [15]:
# Convert 'Date' column to datetime format and then to desired string format
selected_columns['Date'] = pd.to_datetime(selected_columns['Date']).dt.strftime('%d %B %Y')

# Save to Excel
selected_columns.to_excel('Feeding Log with_offset.xlsx', index=False)

print("Data saved to 'Feeding Log with offset.xlsx'.")

Data saved to 'Feeding Log with offset.xlsx'.

C:\Users\junro\AppData\Local\Temp\ipykernel_20292\2416724977.py:5: UserWarning: Pandas requires version '3.0.5' or newer of 'xlsxwriter' (version '3.0.3' currently installed).
  selected_columns.to_excel('Feeding Log with_offset.xlsx', index=False)